#============== Micro Shell MakeFile ============== 

#Project Creators: Bashier Dahman
#Program Information: Micro Shell
#Filename: makefile

####################################################################
# Make File for creating / running executable named msh_assignment #
#                        Bashier Dahman                            #  
####################################################################

# defining our compiler
CC	=	g++

# running g++ and creating the executable file / then running it
all:

	@echo	"Compiling msh_main.cpp"

	$(CC)	-o	msh	msh_main.cpp
	
	@echo	"Now going to run the Mini Shell"
	
	./msh

# this will remove the msh file to clean up the dir.
clean:
	@echo "Now removing 'msh' executable"

	rm	msh
#######################[ EOF: Makefile ]###################
